### ISSUE TITLE
I would like to add your contact details

### ISSUE THREAD

**Issue by Limme996** [Xenooooooooo/optimized_uBlock_algorithm#1]
Hello, I have some questions to ask you. Can you leave your QQ or WeChat contact information?

**Comment by Xenooooooooo** [comment]
you can just write down your questions here, and I'll catch your message via github's email.

**Comment by Limme996** [comment]
Well, I saw in the discussion of the project libOTe that you seem to be testing it, and I'd like to understand and learn what your testing scheme looks like.
I don’t know if it’s convenient to post this here, so I wanted to contact you privately.

**Comment by Xenooooooooo** [comment]
Well, it's a very straightforward thought. libOTe has many environmental parameters, which you can freely make combinations within the limitations, like you cannot build libOTe with cryptoTools down. 

So on one machine, you can have a speed test to figure them out. It's a kind of manual work (lol

**Comment by Limme996** [comment]
Thank you for your reply. I have another question. If I want to run IKNP and Silent OT, can I get the fastest speed by following the original building method of libOTe(  python3 build.py --all --boost --sodium  )

**Comment by Xenooooooooo** [comment]
You have to refer to your own hardward environment.
For example, on my laptop, I get fastest IKNP with ASAN, openssl disabled while other parameters full-on.

You can carry out some experiments and determine your own combination.

**Comment by Xenooooooooo** [comment]
> Thank you for your reply. I have another question. If I want to run IKNP and Silent OT, can I get the fastest speed by following the original building method of libOTe( python3 build.py --all --boost --sodium )

Sorry for the late apply, 2 busy last week. (lol
